### ISSUE TITLE
Can you supply a theme for code in markdown?

### ISSUE THREAD

**Issue by hitzhangjie** [nikrich/jekyll-slender-template#23]
Hi, I really love jekyll-slender-tempalte, it's fascinating!

It works well but the code block in markdown, can you modify some CSS to support the style like {% highlight ruby %} ? Now I write a code block in markdown, the color looks weired.
![image](https://cloud.githubusercontent.com/assets/3725760/24577807/ae5b61c4-1707-11e7-9117-c0d8c0646419.png)

**Comment by nikrich** [comment]
Sure! Do you have this implemented somewhere so that i can see what it looks like?
